// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzAmMResdCsQeCMQcVH7JbS1YzYmor78',
    appId: '1:174163513058:web:e6b805fc3c8f6f1d9518bb',
    messagingSenderId: '174163513058',
    projectId: 'crud-firebase-14524',
    authDomain: 'crud-firebase-14524.firebaseapp.com',
    databaseURL: 'https://crud-firebase-14524-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-14524.firebasestorage.app',
    measurementId: 'G-296GQ27EKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD53jfmGRtfHv8_fx9oAZNJFDoYWxdIFRY',
    appId: '1:174163513058:android:93c97f060dbf284e9518bb',
    messagingSenderId: '174163513058',
    projectId: 'crud-firebase-14524',
    databaseURL: 'https://crud-firebase-14524-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-14524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwDkZhcvOJHweRERR-iqjkPwSF4NES-o',
    appId: '1:174163513058:ios:1638ac5a2d7a015d9518bb',
    messagingSenderId: '174163513058',
    projectId: 'crud-firebase-14524',
    databaseURL: 'https://crud-firebase-14524-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-14524.firebasestorage.app',
    iosBundleId: 'com.example.secureNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpwDkZhcvOJHweRERR-iqjkPwSF4NES-o',
    appId: '1:174163513058:ios:1638ac5a2d7a015d9518bb',
    messagingSenderId: '174163513058',
    projectId: 'crud-firebase-14524',
    databaseURL: 'https://crud-firebase-14524-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-14524.firebasestorage.app',
    iosBundleId: 'com.example.secureNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyzAmMResdCsQeCMQcVH7JbS1YzYmor78',
    appId: '1:174163513058:web:70b7ba2a9eaae0759518bb',
    messagingSenderId: '174163513058',
    projectId: 'crud-firebase-14524',
    authDomain: 'crud-firebase-14524.firebaseapp.com',
    databaseURL: 'https://crud-firebase-14524-default-rtdb.firebaseio.com',
    storageBucket: 'crud-firebase-14524.firebasestorage.app',
    measurementId: 'G-YQ7PRPVW8Y',
  );
}
